# prettier-ignore
env:
  DEPLOY_PATH: ${{ inputs.REMOTE_TARGET }}${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.event_name == 'push' && 'main' || github.event.inputs.destination}}
  # this will:
  #   - start with REMOTE_TARGET, which is usuallly "/var/www/site_name"
  #   - if this is from a PR, use the PR's number for a subdirectory (/var/www/site_name/12)
  #   - if it's a regular commit push, use the main branch (/var/www/site_name/main)
  #   - if there's a "destination" input, meaning it's been manually triggered, use the input value (/var/www/site_name/[value])

name: Site deploy preview

on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true
    inputs:
      REMOTE_TARGET:
        required: true
        type: string
      REMOTE_HOST:
        required: true
        type: string
      REMOTE_USER:
        required: true
        type: string
      PREVIEW_SITE_URL:
        required: true
        type: string

jobs:
    build:
        runs-on: ubuntu-latest # use github runner, not our self-hosted one
        if: |
          github.event_name != 'pull_request_target' ||
          contains('MEMBER OWNER COLLABORATOR', github.event.pull_request.author_association)
        permissions: # set permissions
            pull-requests: write
            contents: read
        steps:
            - name: update PR
              if: ${{ github.event_name == 'pull_request' }} # execute this step only if there is a PR
              uses: thollander/actions-comment-pull-request@v2
              with:
                 message: |
                     Started attempt to build a new deploy preview for PR ${{ github.event.pull_request.number }}.
                 comment_tag: pr_published
            - name: Checkout your repository using git
              uses: actions/checkout@v4 # check out the repo
              with:
                 ref:
                     ${{ github.event_name == 'pull_request' &&
                     github.event.pull_request.head.sha || github.ref }} # if this was triggered by a PR, then match with the commit that the PR uses. otherwise, use the commit that the workflow was triggered from
            - name: install & build
              run: |
                npm install
                npm run build
            - name: upload artifacts # upload the built site so that the next step can access it
              uses: actions/upload-artifact@v4
              with:
                path: |
                  dist/
                  server/
                  package.json
                  package-lock.json

    deploy-website:
        runs-on: ubuntu-latest # github runner, not ours
        if: |
          github.event_name != 'pull_request_target' ||
          contains('MEMBER OWNER COLLABORATOR', github.event.pull_request.author_association)
        permissions:
          pull-requests: write
          contents: read
        needs: build
        steps:
            - uses: actions/download-artifact@v4 # download the artifact from the previous step
              with:
                  name: artifact
            - run: ls -la # debugging step: check if built files downloaded fine & in the right place
            - run: mkdir dist/
            - run: tar -xvf artifact.tar -C dist/
            - run: ls -la
            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@main # deploy via SSH and rsync
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  ARGS: "-rlgoDzvc -i --delete" # flags are: recursive, links (recreate symlinks), groups (match groups on target), owner (match owner on target), devices, compress (smaller file size, makes transfer faster), verbose (for debugging), checksum (this is how rsync checks that an update is needed), itemize changes (list all the changes), delete (get rid of files we don't need)
                  SOURCE: "dist/"
                  REMOTE_HOST: ${{ inputs.REMOTE_HOST }} # the target server to push the deployed site files to
                  REMOTE_USER: ${{ inputs.REMOTE_USER }} # the user that the server will operate as for running the files
                  TARGET: ${{ env.DEPLOY_PATH}} # see line 4 for step-by-step explanation of this variable
                  SCRIPT_AFTER: |
                    cd ${{ env.DEV_DEPLOY_PATH }} # this is used again but to determine what the branch name is and change directories to it
                    # after the files get uploaded, we enter the new directory and install the dependencies now on the server
                    npm install
            - name: update PR
              if: ${{ github.event_name == 'pull_request' }}
              uses: thollander/actions-comment-pull-request@v2 # if there's a PR, update it with a comment that a new deploy preview has been created
              with:
                  message: |
                      Created a new deploy preview for PR ${{ github.event.pull_request.number }}. [See preview](${{ inputs.PREVIEW_SITE_URL }}/${{ github.event.pull_request.number }}/).
                  comment_tag: pr_published
